-- SQL schema derived from JPA entity classes in backend/src/main/java/be/vives/ti/backend/model
-- Target: PostgreSQL

-- Disable referential integrity to allow dropping tables in any order
SET REFERENTIAL_INTEGRITY FALSE;

-- Drop join tables first
DROP TABLE IF EXISTS user_recipes;
DROP TABLE IF EXISTS user_crops;

-- Drop FK constraints on snake_case tables (if present)
ALTER TABLE IF EXISTS recipe_quantities DROP CONSTRAINT IF EXISTS fk_rq_ingredient;
ALTER TABLE IF EXISTS recipe_quantities DROP CONSTRAINT IF EXISTS fk_rq_recipe;
ALTER TABLE IF EXISTS recipe_quantities DROP CONSTRAINT IF EXISTS fk_rq_measurement;
ALTER TABLE IF EXISTS recipes DROP CONSTRAINT IF EXISTS fk_recipes_author;
ALTER TABLE IF EXISTS recipes DROP CONSTRAINT IF EXISTS fk_recipes_course;
ALTER TABLE IF EXISTS recipes DROP CONSTRAINT IF EXISTS fk_recipes_category;
ALTER TABLE IF EXISTS recipe_steps DROP CONSTRAINT IF EXISTS fk_rs_recipe;
ALTER TABLE IF EXISTS ingredients DROP CONSTRAINT IF EXISTS fk_ingredients_crop;
ALTER TABLE IF EXISTS user_crops DROP CONSTRAINT IF EXISTS fk_usercrops_crop;
ALTER TABLE IF EXISTS user_crops DROP CONSTRAINT IF EXISTS fk_usercrops_user;
ALTER TABLE IF EXISTS user_recipes DROP CONSTRAINT IF EXISTS fk_userrecipes_recipe;
ALTER TABLE IF EXISTS user_recipes DROP CONSTRAINT IF EXISTS fk_userrecipes_user;

-- Now drop tables in dependency order
DROP TABLE IF EXISTS recipe_quantities;
DROP TABLE IF EXISTS recipe_steps;
DROP TABLE IF EXISTS ingredient_measurements;
DROP TABLE IF EXISTS ingredients;
DROP TABLE IF EXISTS recipes;
DROP TABLE IF EXISTS courses;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS crops;
DROP TABLE IF EXISTS users;

SET REFERENTIAL_INTEGRITY TRUE;



-- Users table
CREATE TABLE users (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_name varchar(100) NOT NULL,
  user_email varchar(255) NOT NULL,
  password varchar(255) NOT NULL,
  role varchar(20) NOT NULL
);

-- Crops
CREATE TABLE crops (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cropname varchar(255),
  sowing_start smallint,
  sowing_end smallint,
  planting_start smallint,
  planting_end smallint,
  harvest_start smallint,
  harvest_end smallint,
  in_house boolean,
  in_pots boolean,
  in_garden boolean,
  in_greenhouse boolean,
  crop_description text,
  crop_tips text,
  image varchar(1024)
);

-- Categories
CREATE TABLE categories (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_name varchar(255)
);

-- Courses
CREATE TABLE courses (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_name varchar(255)
);

-- Ingredient measurements
CREATE TABLE ingredient_measurements (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  measurement_name varchar(255)
);

-- Ingredients
CREATE TABLE ingredients (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ingredient_name varchar(255),
  crop_id integer,
  CONSTRAINT fk_ingredients_crop FOREIGN KEY (crop_id) REFERENCES crops(id) ON DELETE SET NULL
);

-- Recipes
CREATE TABLE recipes (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recipe_name varchar(255),
  author integer,
  recipe_description text,
  prep_time varchar(255),
  cook_time varchar(255),
  image varchar(1024),
  course_id integer,
  category_id integer,
  CONSTRAINT fk_recipes_author FOREIGN KEY (author) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_recipes_course FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE SET NULL,
  CONSTRAINT fk_recipes_category FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL
);

-- Recipe quantities (join between recipe and ingredient + measurement)
CREATE TABLE recipe_quantities (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recipe_id integer,
  ingredient_id integer,
  measurement_id integer,
  quantity numeric(38,2),
  CONSTRAINT fk_rq_recipe FOREIGN KEY (recipe_id) REFERENCES recipes(id) ON DELETE CASCADE,
  CONSTRAINT fk_rq_ingredient FOREIGN KEY (ingredient_id) REFERENCES ingredients(id) ON DELETE CASCADE,
  CONSTRAINT fk_rq_measurement FOREIGN KEY (measurement_id) REFERENCES ingredient_measurements(id) ON DELETE SET NULL
);

-- Recipe steps
CREATE TABLE recipe_steps (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  step_number integer,
  step_description text,
  recipe_id integer,
  CONSTRAINT fk_rs_recipe FOREIGN KEY (recipe_id) REFERENCES recipes(id) ON DELETE CASCADE
);

-- Many-to-many user favorite crops. Note: entity declared join columns as cropID (joinColumns) and userID (inverseJoinColumns)
CREATE TABLE user_crops (
  crop_id integer NOT NULL,
  user_id integer NOT NULL,
  PRIMARY KEY (crop_id,user_id),
  CONSTRAINT fk_usercrops_crop FOREIGN KEY (crop_id) REFERENCES crops(id) ON DELETE CASCADE,
  CONSTRAINT fk_usercrops_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Many-to-many user favorite recipes. Entity defines joinColumns recipeID and inverseJoinColumns userID
CREATE TABLE user_recipes (
  recipe_id integer NOT NULL,
  user_id integer NOT NULL,
  PRIMARY KEY (recipe_id,user_id),
  CONSTRAINT fk_userrecipes_recipe FOREIGN KEY (recipe_id) REFERENCES recipes(id) ON DELETE CASCADE,
  CONSTRAINT fk_userrecipes_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Indexes
CREATE INDEX idx_recipes_author ON recipes(author);
CREATE INDEX idx_recipe_quantities_recipe ON recipe_quantities(recipe_id);
CREATE INDEX idx_recipe_steps_recipe ON recipe_steps(recipe_id);
CREATE INDEX idx_ingredients_crop ON ingredients(crop_id);

-- End of schema
