import { StyleSheet } from 'react-native';

const common = StyleSheet.create({
  container: { flex: 1 },
  header: { flexDirection: 'row', padding: 14, borderBottomWidth: 1 },
  title: { fontSize: 26, fontWeight: '700' },
  subtitle: { fontSize: 16 },
  card: { marginHorizontal: 20, marginBottom: 14, borderRadius: 12, overflow: 'hidden', borderWidth: 1 },
  cardHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 },
  cardTitle: { fontSize: 18, fontWeight: '600' },
  cardSubtitle: { fontSize: 14, lineHeight: 20 },
  cardImage: { width: '100%', height: 140 },
  cardBody: { padding: 14 },
  cardNumber: { fontSize: 32, fontWeight: 'bold' },
  segment: { flex: 1, paddingVertical: 8, borderRadius: 8, alignItems: 'center', marginHorizontal: 6 },
  segmentText: { fontWeight: '700' },
  viewButton: { marginTop: 8, paddingVertical: 8, paddingHorizontal: 12, borderRadius: 8, alignSelf: 'flex-start' },
  viewButtonText: { color: '#fff', fontWeight: '700' },
  heartOverlay: { width: 28, height: 28, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  primaryButton: { borderRadius: 10, paddingVertical: 14, paddingHorizontal: 16, alignItems: 'center', justifyContent: 'center' },
  primaryButtonText: { color: '#FFF', fontWeight: '700', fontSize: 16 },
  featureCard: { marginHorizontal: 20, marginBottom: 20, borderRadius: 12, overflow: 'hidden', borderWidth: 1 },
  featureImagePlaceholder: { height: 180 },
  featureContent: { padding: 16 },
  featureTitle: { fontSize: 20, fontWeight: 'bold' },
  featureDescription: { fontSize: 15, marginBottom: 16, lineHeight: 22 },
  featureButton: { paddingVertical: 12, borderRadius: 8, alignItems: 'center' },
  featureButtonText: { color: '#FFF', fontSize: 16, fontWeight: '600' },
  searchInput: { height: 48, borderRadius: 10, paddingHorizontal: 14, borderWidth: 1 },
  stateWrapper: { alignItems: 'center', justifyContent: 'center', paddingVertical: 40 },
  listContent: { paddingBottom: 24 },

  headerWrap: { padding: 18 },
  wrapper: { flex: 1 },
  titleText: { fontSize: 26, fontWeight: '700' },
  cardImageWrapper: { height: 140, backgroundColor: '#eee' },
  logoCircle: { width: 68, height: 68, borderRadius: 34, justifyContent: 'center', alignItems: 'center' },
  logoIcon: { color: '#fff', fontSize: 30 },
  input: { height: 48, borderRadius: 8, paddingHorizontal: 14, borderWidth: 1, marginBottom: 12 },
  label: { fontSize: 13, marginBottom: 6 },
  signInButton: { height: 48, borderRadius: 8, justifyContent: 'center', alignItems: 'center', paddingHorizontal: 12 },
  signInText: { color: '#fff', fontWeight: '700', fontSize: 15 },
  editButton: { paddingHorizontal: 12, paddingVertical: 6, borderRadius: 8, borderWidth: 1 },
  editText: { fontWeight: '700' },
  avatar: { width: 68, height: 68, borderRadius: 34, justifyContent: 'center', alignItems: 'center' },
  profileName: { fontSize: 18, fontWeight: '700' },
  profileEmail: { fontSize: 14 },
  statCard: { flexDirection: 'row', alignItems: 'center', padding: 14, borderRadius: 12, borderWidth: 1, marginTop: 10 },
  statNumber: { fontSize: 20, fontWeight: '700' },
  statLabel: { fontSize: 13 },
});

export default common;
